"""Per-turn LOOM.md retrieval via BM25 — the loominit slice 3 unlock.

The problem this solves
-----------------------

Without this module, ``LOOM.md`` is read once at startup and inlined
verbatim into every system prompt (truncated to 8KB if larger). For
a 50KB LOOM.md generated by the annotator, that means 42KB is
discarded at startup AND the surviving 8KB is shipped on every turn
even when the user's prompt only touches one subsystem. Both halves
of that are waste.

What this module does
---------------------

* Parses ``LOOM.md`` into sections on ``##`` heading boundaries.
* Builds a tiny in-process BM25 index over section text (no extra
  pip dep — the scorer is ~40 lines of standard formula at the
  bottom of this file).
* On each user turn, the REPL calls
  :meth:`LoomRetriever.relevant(user_prompt)` and gets back a
  rendered block containing the top-N most relevant sections.
* The REPL writes that block via ``memory.update_block(...)``;
  loomflow auto-injects working blocks into every subsequent
  system prompt — so the coordinator sees the 2-3 sections that
  matter for THIS turn instead of the whole index.

What this module deliberately does NOT do
-----------------------------------------

* No staleness wrapping (slice 4 will wrap claims whose source-hash
  drifted with ``(stale)``). For now the retrieval is dumb — it
  hands back whatever the annotator wrote.
* No semantic / embedding retrieval. BM25 is cheap, zero-dep,
  deterministic, and works well on the structured-prose form the
  annotator emits. Embeddings are a later upgrade.
* No re-ranking, query expansion, hybrid fusion. The corpus is
  tiny (a typical LOOM.md is 20-100 sections) — BM25 alone is more
  than enough.

Token budget
------------

``max_chars`` caps the rendered block. A typical section is
500-1500 chars; top-3 selection keeps the block under ~5KB
worst-case. Versus the old "inline 8KB of LOOM.md on every turn"
shape, the worst case is roughly the same size — but the bytes
shipped are *targeted at the current turn* rather than random.
On a relevant query the win is most of the prompt; on an irrelevant
query, the working block is at worst no bigger than the old
verbatim bake.
"""

from __future__ import annotations

import math
import re
from collections.abc import Iterable
from dataclasses import dataclass, field
from pathlib import Path

from .persistence import markdown_path, read_markdown

# Working-block name the REPL writes into. Stable string so other
# loom-code surfaces (telemetry, debug logging, manual inspection of
# ``/blocks``) can name the same thing.
LOOM_BLOCK_NAME = "loom_index"


@dataclass(slots=True)
class _Section:
    """One ``##`` section of LOOM.md.

    ``heading`` is the literal heading text without the ``##`` prefix
    (e.g. ``"Workspace internals"``). ``body`` is everything between
    this heading and the next one. ``tokens`` is the tokenised body
    cached for BM25 scoring.
    """

    heading: str
    body: str
    tokens: list[str] = field(default_factory=list)


_TOKEN_RE = re.compile(r"[A-Za-z][A-Za-z0-9_]+")
# ``_STOPWORDS`` — the tiny set of high-frequency English glue
# words that dilute BM25 scores. NOT a full stopword list (BM25's
# IDF already down-weights common terms); just the ones that show
# up in every section of LOOM.md and would otherwise inflate
# false-positive matches.
_STOPWORDS = frozenset(
    {
        "the",
        "and",
        "for",
        "with",
        "from",
        "that",
        "this",
        "are",
        "has",
        "have",
        "into",
        "but",
        "not",
    }
)


def _tokenize(text: str) -> list[str]:
    """Lowercase, identifier-only tokenisation.

    Identifier shape (``[A-Za-z][A-Za-z0-9_]+``) is the right
    granularity for code-adjacent prose — preserves
    ``snake_case`` / ``camelCase`` symbols intact while dropping
    punctuation. Stopwords are filtered AFTER lowercasing so the
    set matching is case-blind.
    """
    return [
        tok
        for tok in (m.group(0).lower() for m in _TOKEN_RE.finditer(text))
        if tok not in _STOPWORDS
    ]


def parse_sections(markdown: str) -> list[_Section]:
    """Split LOOM.md into ``##`` sections.

    Splits on level-2 headings (``## Title``). The leading content
    before the first ``##`` becomes an "(intro)" section so it stays
    searchable — annotators usually put project-level overview there.

    Empty bodies (heading-only lines, blank sections) are dropped so
    BM25 has only real content to score over.
    """
    lines = markdown.splitlines()
    sections: list[_Section] = []

    current_heading = "(intro)"
    current_body: list[str] = []

    for line in lines:
        # Only ``## `` (level 2). ``### `` and ``# `` are sub-
        # sections / document title and don't split.
        m = re.match(r"^##\s+(.+?)\s*$", line)
        if m:
            if current_body:
                body = "\n".join(current_body).strip()
                if body:
                    sections.append(
                        _Section(
                            heading=current_heading,
                            body=body,
                            tokens=_tokenize(
                                f"{current_heading}\n{body}"
                            ),
                        )
                    )
            current_heading = m.group(1).strip()
            current_body = []
        else:
            current_body.append(line)

    # Tail section (the part after the last ``##``).
    if current_body:
        body = "\n".join(current_body).strip()
        if body:
            sections.append(
                _Section(
                    heading=current_heading,
                    body=body,
                    tokens=_tokenize(f"{current_heading}\n{body}"),
                )
            )

    return sections


@dataclass(slots=True)
class _Bm25Index:
    """In-process BM25 corpus.

    Built once when the retriever loads. ``avg_dl`` is the average
    document length used by the BM25 length-normalisation term.
    ``idf`` precomputes the inverse-document-frequency for every
    distinct token in the corpus — recomputing on every query would
    be wasteful.

    ``k1`` and ``b`` are the canonical BM25 hyperparameters:
    ``k1=1.5`` (term-frequency saturation) and ``b=0.75`` (length
    normalisation strength) are the standard defaults that BM25 was
    originally tuned against.
    """

    docs: list[_Section]
    idf: dict[str, float]
    avg_dl: float
    k1: float = 1.5
    b: float = 0.75

    def score(self, query_tokens: Iterable[str]) -> list[float]:
        """Return one score per document in ``self.docs``."""
        scores = [0.0] * len(self.docs)
        for q in query_tokens:
            idf = self.idf.get(q)
            if idf is None:
                continue
            for i, doc in enumerate(self.docs):
                tf = doc.tokens.count(q)
                if tf == 0:
                    continue
                dl = len(doc.tokens) or 1
                denom = tf + self.k1 * (
                    1.0 - self.b + self.b * (dl / self.avg_dl)
                )
                scores[i] += idf * (tf * (self.k1 + 1.0)) / denom
        return scores


def _build_index(docs: list[_Section]) -> _Bm25Index:
    """Compute IDF + average document length for the corpus."""
    n = len(docs)
    if n == 0:
        return _Bm25Index(docs=[], idf={}, avg_dl=0.0)
    df: dict[str, int] = {}
    for doc in docs:
        for tok in set(doc.tokens):
            df[tok] = df.get(tok, 0) + 1
    # Standard BM25 IDF with the +1 smoothing to keep IDF > 0
    # even for terms present in every document.
    idf = {
        tok: math.log(1.0 + (n - dfreq + 0.5) / (dfreq + 0.5))
        for tok, dfreq in df.items()
    }
    avg_dl = sum(len(d.tokens) for d in docs) / n
    return _Bm25Index(docs=docs, idf=idf, avg_dl=avg_dl)


class LoomRetriever:
    """Per-turn BM25 retrieval over ``LOOM.md`` sections.

    Lifecycle: built once per REPL session via
    :meth:`from_repo_root`. Returns ``None`` when no ``LOOM.md``
    exists (the user never ran ``/loominit``) — callers should treat
    that as "no retriever, fall back to the static context block."

    On every ``coord.run()``, the REPL passes the user's prompt to
    :meth:`relevant`; the result goes into a working memory block
    via the loomflow ``memory.update_block`` API.
    """

    def __init__(
        self,
        sections: list[_Section],
        *,
        top_n: int = 3,
        max_chars: int = 4000,
    ) -> None:
        self._sections = sections
        self._index = _build_index(sections)
        self._top_n = max(1, top_n)
        # ``max_chars`` is the rendered-block cap. 4000 ≈ 1000
        # tokens for English prose — comparable to the old static
        # bake but targeted per-turn.
        self._max_chars = max_chars

    @classmethod
    def from_repo_root(
        cls,
        repo_root: Path,
        *,
        top_n: int = 3,
        max_chars: int = 4000,
    ) -> LoomRetriever | None:
        """Load + parse ``<repo_root>/LOOM.md``. Returns ``None`` if
        the file is absent or empty."""
        text = read_markdown(repo_root)
        if not text or not text.strip():
            return None
        sections = parse_sections(text)
        if not sections:
            return None
        return cls(sections, top_n=top_n, max_chars=max_chars)

    @property
    def is_loaded(self) -> bool:
        """True when the retriever has at least one searchable
        section. Drives REPL conditional logic ("only show LOOM
        block when we actually have one")."""
        return bool(self._sections)

    @property
    def section_count(self) -> int:
        return len(self._sections)

    def relevant(self, query: str) -> str:
        """Return a markdown block of the top-N most-relevant sections.

        Empty string when:
        * the retriever has no sections
        * the query produced zero non-zero BM25 scores (no token
          overlap with any section)

        The renderer prefixes each section with its original heading
        so the model knows which subsystem the snippet belongs to.
        Sections are truncated to fit under ``max_chars`` total.
        """
        if not self._sections:
            return ""
        tokens = _tokenize(query)
        if not tokens:
            return ""
        scores = self._index.score(tokens)
        # Sort by score descending; drop zeros (no token overlap →
        # no signal). The fallback "include everything" would
        # defeat the purpose of retrieval — better to return ""
        # and let the system prompt stay lean.
        ranked = sorted(
            (
                (i, s)
                for i, s in enumerate(scores)
                if s > 0
            ),
            key=lambda pair: pair[1],
            reverse=True,
        )
        if not ranked:
            return ""
        picked: list[_Section] = []
        total_chars = 0
        for i, _ in ranked[: self._top_n]:
            sec = self._sections[i]
            # Header + body + a blank line.
            chunk_len = len(sec.heading) + len(sec.body) + 8
            if total_chars + chunk_len > self._max_chars and picked:
                # Stop when adding the next section would exceed the
                # budget — but only if we've picked at least one
                # (avoid returning a useful-but-too-big section as
                # "" just because it alone exceeds the cap).
                break
            picked.append(sec)
            total_chars += chunk_len
        if not picked:
            return ""
        body_parts = [
            f"## {sec.heading}\n{sec.body}" for sec in picked
        ]
        header = (
            f"# Relevant LOOM.md sections "
            f"({len(picked)} of {len(self._sections)}, "
            f"BM25-retrieved per turn)\n"
        )
        return header + "\n\n".join(body_parts)

    def loom_path(self, repo_root: Path) -> Path:
        """Convenience for telemetry / debug — where the source
        file lives."""
        return markdown_path(repo_root)
